### ISSUE TITLE
FUNSD test result is very low!

### ISSUE THREAD

**Issue by weishu20** [andreagemelli/doc2graph#1] opened 2022-12-05 11:00 UTC
Hi,I tried your public model to test FUNSD,but get low result,is some thing wrong?
I tried edge model and e2e model
<img width="330" alt="截屏2022-12-05 下午6 56 30" src="https://user-images.githubusercontent.com/23519687/205621222-6d921b2a-23c2-4c66-8f55-98cfefd016f7.png">
<img width="313" alt="截屏2022-12-05 下午6 55 08" src="https://user-images.githubusercontent.com/23519687/205621303-dd1178ed-33fa-4189-8686-262fab51fa85.png">

**Comment by weishu20** [comment] 2022-12-05 11:03
@andreagemelli

**Comment by andreagemelli** [comment] 2022-12-05 11:23
Hi,
Probably there are some problems with the weights. I will try to fix it asap, let you know.
A.

**Comment by weishu20** [comment] 2022-12-06 02:06
And I tried to train e2e model on FUNSD,but I cant get good result as paper‘s？
<img width="330" alt="截屏2022-12-06 上午9 59 57" src="https://user-images.githubusercontent.com/23519687/205790954-582d92c5-184a-4800-9347-fcbc455cf871.png">

**Comment by weishu20** [comment] 2022-12-06 03:36
for Semantic Entity Labeling, the paper's best F1 is 0.82,is equal to node micro I tried(0.8105)?
for Entity Linking,best F1 is 0.53 in paper,which metric matches the above？
None=0.9964;Key-Value=0.5895;AUC-PR=0.7903 in paper is higher ?
Thanks for answering^^

**Comment by andreagemelli** [comment] 2022-12-07 12:15
Thanks for the feedbacks!
I cannot currently work on the bug, I can get a look at it during the next week! I will let you know.

**Comment by andreagemelli** [comment] 2022-12-16 09:36
Hey @weishu20,
I did not forget about you!
While I have solved other minor issue with the last commit, we are still struggling with the results: in the image you can see that on the left, in another machine where I installed again the repo, the results are low like yours. While, in my server, the results are still the one I experimented with for the publication. 
We believe that the problem is in the construction of the graph or the features used by the nodes. We already excluded data and weights for the possible problems.
I hope to get back to you asap.

![Screenshot 2022-12-14 at 14 41 36](https://user-images.githubusercontent.com/32863289/208068280-84025823-6418-40b2-8e29-e5c4d7109426.png)

**Comment by andreagemelli** [comment] 2023-01-02 19:00
Hi @weishu20 ,
sorry for my late answer.
Going through the code I have noticed that in the meantime we published the code spaCy came out with a new version of its language models, including the one used by Doc2Graph. As a results, the textual features loaded during the preprocessing were completely different from the ones in my original repo.
I tried myself to reproduce the behaviour of my repo into a new and different environment and now the problem should be fixed: please reinstall the library following the new README.md file and let me know!
A.

**Closed as completed by andreagemelli** 2023-01-02 19:00 UTC
